/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-router. ‼️ DO NOT MODIFY THIS FILE ‼️
// It's recommended to commit this file.
// Make sure to add this file to your tsconfig.json file as an "includes" or "files" entry.

declare module 'vue-router/auto-routes' {
  import type {
    RouteRecordInfo,
    ParamValue,
    ParamValueOneOrMore,
    ParamValueZeroOrMore,
    ParamValueZeroOrOne,
  } from 'vue-router'

  /**
   * Route name map generated by unplugin-vue-router
   */
  export interface RouteNamedMap {
    '/financial/rent-and-debts/': RouteRecordInfo<'/financial/rent-and-debts/', '/financial/rent-and-debts', Record<never, never>, Record<never, never>>,
    '/financial/rent-and-debts/components/bill-card/BillCard': RouteRecordInfo<'/financial/rent-and-debts/components/bill-card/BillCard', '/financial/rent-and-debts/components/bill-card/BillCard', Record<never, never>, Record<never, never>>,
    '/financial/rent-and-debts/components/financial-card/FinancialCard': RouteRecordInfo<'/financial/rent-and-debts/components/financial-card/FinancialCard', '/financial/rent-and-debts/components/financial-card/FinancialCard', Record<never, never>, Record<never, never>>,
    '/home/': RouteRecordInfo<'/home/', '/home', Record<never, never>, Record<never, never>>,
    '/login/': RouteRecordInfo<'/login/', '/login', Record<never, never>, Record<never, never>>,
    '/register/': RouteRecordInfo<'/register/', '/register', Record<never, never>, Record<never, never>>,
  }
}
